### ISSUE TITLE
Error in "RobotHardware.update": invalid literal for int()

### ISSUE THREAD

**Issue by kayhe** [zauberzeug/rosys#156]
Hello,

after our Robot Brain was modified to include another serial port, rosys communication with the microcontroller of the Brain seems to be broken, as an non numeric string is cast to an integer.

```
rosys_1       | 2024-07-25 13:43:32.282 [ERROR] rosys/rosys.py:206: error in "RobotHardware.update"
rosys_1       | Traceback (most recent call last):
rosys_1       |   File "/app/rosys/rosys.py", line 200, in _repeat_one_handler
rosys_1       |     await invoke(handler)
rosys_1       |   File "/app/rosys/helpers/__init__.py", line 36, in invoke
rosys_1       |     result = await result
rosys_1       |              ^^^^^^^^^^^^
rosys_1       |   File "/app/rosys/hardware/robot.py", line 66, in update
rosys_1       |     cast(ModuleHardware, module).handle_core_output(time, words)
rosys_1       |   File "/app/rosys/hardware/estop.py", line 52, in handle_core_output
rosys_1       |     corelist = [int(words.pop(0)) == 0 for _ in self.pins]
rosys_1       |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1       |   File "/app/rosys/hardware/estop.py", line 52, in <listcomp>
rosys_1       |     corelist = [int(words.pop(0)) == 0 for _ in self.pins]
rosys_1       |                 ^^^^^^^^^^^^^^^^^
rosys_1       | ValueError: invalid literal for int() with base 10: '"rs485_v04"'

```

Reading the startup checksum and Lizard version from Core and P0 fails as well.

Any help would be appreciated.

Greetings,
Kay

**Comment by pascalzauberzeug** [comment]
Hey Kay, 
the string "rs485_v04" is part of our lizard configuration for testing the brain.
Did you already try to reconfigure the ESPs in the field_friend ui?

**Comment by kayhe** [comment]
Flashing the ESPs via UI seems to be working, according to the logs.

```
rosys_1       | Wrote 1617488 bytes (917901 compressed) at 0x00020000 in 13.1 seconds (effective 984.3 kbit/s)...
rosys_1       | Hash of data verified.
rosys_1       | 
rosys_1       | Leaving...
rosys_1       | Hard resetting via RTS pin...
rosys_1       | Initializing ESP...
rosys_1       | Configuring pins...
```

Reading back the Lizard version afterwards fails though, and the ValueError occurs.
Somehow I cannot find the 'rs485_v04' anywhere in the source code on our robot.

**Comment by pascalzauberzeug** [comment]
I will try to find the problem on your robot remotely, if that's ok with you.

**Comment by kayhe** [comment]
That's fine. I'll let it charge and leave it on over night

**Comment by pascalzauberzeug** [comment]
I think I fixed it. 0.2.0 is now on both ESPs.
Seems like there is a problem with flashing p0 via ui, because it worked when I flashed p0 via [monitor.py](https://github.com/zauberzeug/lizard/blob/main/monitor.py).

Please report back when you tested it

**Comment by kayhe** [comment]
Yes, the robot works as expected again.

In the logs I found an AssertionError pertaining to RobotHardware.update, though.

```
rosys_1       | 2024-07-26 11:28:56.777 [ERROR] rosys/rosys.py:206: error in "RobotHardware.update"
rosys_1       | Traceback (most recent call last):
rosys_1       |   File "/app/rosys/rosys.py", line 200, in _repeat_one_handler
rosys_1       |     await invoke(handler)
rosys_1       |   File "/app/rosys/helpers/__init__.py", line 36, in invoke
rosys_1       |     result = await result
rosys_1       |              ^^^^^^^^^^^^
rosys_1       |   File "/app/rosys/hardware/robot.py", line 70, in update
rosys_1       |     cast(ModuleHardware, module).message_hooks[words[0]](line)
rosys_1       |   File "/app/rosys/hardware/bms.py", line 77, in _handle_bms
rosys_1       |     msg.check()
rosys_1       |   File "/app/rosys/hardware/bms_message.py", line 29, in check
rosys_1       |     assert (self.bytes[-3] << 8) + self.bytes[-2] == 0xffff - sum(self.content) - self.length - self.status + 1
rosys_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rosys_1       | AssertionError

```

**Comment by pascalzauberzeug** [comment]
I think this is just a problem on startup since the battery percentage is displayed normally, but I will check it and get back to you

**Comment by pascalzauberzeug** [comment]
The assertionerror should be a timing problem when Rosys is restarting, so you can ignore it, since it works afterwards.
I will close this issue now.
