### ISSUE TITLE
import rosys does not work with ui.run(reload=False) - RuntimeError: multiprocessing start method must be "spawn"

### ISSUE THREAD

**Issue by AndyPermaRobotics** [zauberzeug/rosys#19]
Hello everyone,

I have come across the following error message when I set the reload flag to False in the ui.run function:
```
 Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/nicegui/background_tasks.py", line 55, in _handle_task_result
  task.result()
File "/usr/local/lib/python3.11/site-packages/nicegui/helpers.py", line 77, in result_with_client
  await result
File "/rosys/rosys/rosys.py", line 144, in startup
  raise RuntimeError(
RuntimeError: multiprocessing start method must be "spawn"; see https://pythonspeed.com/articles/python-multiprocessing/
```

To better localize the source of the error, I have created a minimal example where the error occurs. Just `import rosys` is enough.

Example:
```python
from nicegui import ui

import rosys

ui.run(
    title='Test', 
    port=8080,
    reload=False
    )
```

The error also occurs when I try to plan a path in my main program.

--- 
**How did I come up with the idea of setting reload=False?**

The reload flag causes my script to run twice. This results in two instances of each class being created. This has caused problems when I tried to subscribe to an MQTT topic, and my callback function was suddenly called twice for each message. The reload does not seem to be a complete restart where all resources from the previous run are cleaned up.

**Comment by AndyPermaRobotics** [comment]
@rodja thanks for the link to the FAQ, my script works now.

It's interesting, that you could not reproduce the issue on MacOS.
I let it run in a Docker Container.

Dockerfile:
```

FROM zauberzeug/rosys:latest 

WORKDIR /usr/src/app
```

docker-compose.yml
```yml
version: "3.9"
services:
  rosys_service:
    build: .
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    hostname: docker
```

**Comment by rodja** [comment]
Ah very good @AndyPermaRobotics. With Docker the error comes up as described by you. I've just tested locally on mac.

**Comment by rodja** [comment]
No, I have not looked into it.

**Comment by NiklasNeugebauer** [comment]
I looked into this a little. I think the best way to solve this may be keeping Nicegui's behavior consistent in case there is no specific reason that it does not set the spawn method when `reload=False`. However, I do not understand enough about Nicegui to fix this.

Another Option would be forcing the method to spawn instead of raising an exception in rosys.py `on_startup`:
multiprocessing.set_start_method('spawn', force=True)

**Comment by falkoschindler** [comment]
Almost three years later and with https://github.com/zauberzeug/nicegui/pull/6065 merged just recently, I asked Claude to look into this issue. Seems like there is a solution in sight:

### Diagnosis and a possible fix

The error is raised by the global multiprocessing-start-method check in `startup()` ([`rosys/rosys.py:235-237`](https://github.com/zauberzeug/rosys/blob/main/rosys/rosys.py#L235-L237)). RoSys requires the **global** start method to be `"spawn"`, but never reliably sets it itself: the `multiprocessing.set_start_method('spawn')` at [`rosys/rosys.py:33-34`](https://github.com/zauberzeug/rosys/blob/main/rosys/rosys.py#L33-L34) is guarded by `if __name__ == '__main__':`, and since this is an imported module (`rosys.rosys`), `__name__` is never `'__main__'` — that line is effectively dead. RoSys is therefore relying entirely on NiceGUI/uvicorn to have flipped the global default to spawn.

That explains the `reload` dependence:

- With `reload=True` (default), uvicorn's reloader spawns worker subprocesses and spawn ends up in effect.
- With `reload=False`, no reloader runs, so on Linux/Docker the global default stays `fork` (and on Python 3.14+ it is now `forkserver`) → the check fires. This is also why it reproduces in Docker but not on macOS, where spawn is already the default.

The global spawn requirement exists for exactly one reason: the path-planner subprocess (`PlannerProcess(Process)` in [`rosys/pathplanning/planner_process.py:60`](https://github.com/zauberzeug/rosys/blob/main/rosys/pathplanning/planner_process.py#L60)) and its `Pipe()` ([`rosys/pathplanning/path_planner.py:38`](https://github.com/zauberzeug/rosys/blob/main/rosys/pathplanning/path_planner.py#L38)) must not use `fork`. `run.cpu()` is not affected — it delegates to `nicegui.run`, which manages its own spawn-context pool.

### Possible fix

NiceGUI recently solved the equivalent problem in zauberzeug/nicegui#6065 (finishing zauberzeug/nicegui#6045): instead of depending on the global start method, it created `SPAWN_CONTEXT = multiprocessing.get_context('spawn')` and routes every primitive through it (`SPAWN_CONTEXT.Process(...)`, `.Queue()`, `.Pipe()`, `.Event()`). The subprocess then uses spawn regardless of the OS default — robust against both `reload=False` and Python 3.14's `forkserver` switch.

RoSys can apply the same pattern, scoped to the path planner:

1. Create `ctx = multiprocessing.get_context('spawn')`; base `PlannerProcess` on `ctx.Process` (resolves to the subclassable `SpawnProcess`) and create the pipe via `ctx.Pipe()`.
2. Remove the global check in `startup()` and the dead `set_start_method` block at the top, since spawn is no longer a global precondition.
3. The `enforce_spawn_process` test fixture ([`rosys/testing/fixtures.py:74`](https://github.com/zauberzeug/rosys/blob/main/rosys/testing/fixtures.py#L74)) then becomes unnecessary.

This is preferable to the `set_start_method('spawn', force=True)` workaround mentioned earlier in this thread, which mutates global process state and can clash with whatever the host application does.

Worth verifying when implementing: that the spawned child re-imports cleanly (spawn re-imports the module, so the planner target must be import-safe — it already is, since it is a class, not module-level code).

**Comment by evnchn** [comment]
I think yes, but the Q is: HMW reliably ensure the RoSys equivalent of zauberzeug/nicegui#6065 doesn't happen, and we hit it one-shot?

This is gonna be hard as much more spawning is done in RoSys compared to NiceGUI, and much higher stakes I'd imagine...
